name: Python CI with autopep8
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  autopep8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 检出代码

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install autopep8
        run: |
          pip install autopep8

      - name: Run autopep8 to fix PEP 8 issues
        run: |
          autopep8 --in-place --aggressive --recursive .
     
      - name: Check for changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
            exit 0
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "talented-watermelon"
          git config --global user.email "1980207347@qq.com"
          git add .
          git commit -m "Fix PEP 8 issues"
          git push
        if: ${{ success() }}
